// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Ajuste aquí para soportar web
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyChAHyTquA3dyzEn4wHIUZCzKl1KY8rbP8",
      authDomain: "appecommerce-8ffe6.firebaseapp.com",
      projectId: "appecommerce-8ffe6",
      storageBucket: "appecommerce-8ffe6.appspot.com",
      messagingSenderId: "878873479020",
      appId: "1:878873479020:web:947eb691389a3ace369549",
      measurementId: "G-SHXY7TBMFK"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5UYyjjaaAcFiCfqJgrXX9balLxUKNA9I',
    appId: '1:878873479020:android:3910b7cb9d7a64b8369549',
    messagingSenderId: '878873479020',
    projectId: 'appecommerce-8ffe6',
    storageBucket: 'appecommerce-8ffe6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGfQFfbbfue5fVM1h1L8URT481AumwZPg',
    appId: '1:878873479020:ios:c09b13f975c29bf3369549',
    messagingSenderId: '878873479020',
    projectId: 'appecommerce-8ffe6',
    storageBucket: 'appecommerce-8ffe6.appspot.com',
    androidClientId: '878873479020-iks31roppcmd5he2te9bslfavdlj09sq.apps.googleusercontent.com',
    iosClientId: '878873479020-f1uv7dbh29sqpfnv1ut15jeh8nbtvrtq.apps.googleusercontent.com',
    iosBundleId: 'com.example.appEcommerce',
  );
}